from .builders import build_docs_view, build_empty_view
from .models import EMPTY_NAVIGATION_STATE, DocsPageView, EmptyPageView, NavigationState, SidebarView
from .nav import render_nav_items
from .shell import (
    base_document,
    docs_shell,
    empty_shell,
    floating_theme_picker,
    main_shell,
    render_docs_fragment,
    render_docs_page,
    render_empty_fragment,
    render_empty_page,
    render_search_results_fragment,
    render_sidebar_fragment,
    search_chrome,
    sidebar_shell,
    theme_picker,
)
from .support import (
    MAIN_SHELL_ID,
    NAV_QUERY_PARAM,
    NAV_STATE_QUERY_PARAM,
    SIDEBAR_SHELL_ID,
    SIDEBAR_STATE_FORM_ID,
    docs_href,
    enhance_markdown_links,
    extract_title,
    htmx_nav_attrs,
    htmx_nav_html_attrs,
    htmx_request_href,
    htmx_sidebar_attrs,
    icon_href,
    public_asset_href,
    with_nav_open_paths,
)

__all__ = [
    "DocsPageView",
    "EMPTY_NAVIGATION_STATE",
    "EmptyPageView",
    "MAIN_SHELL_ID",
    "NAV_QUERY_PARAM",
    "NAV_STATE_QUERY_PARAM",
    "NavigationState",
    "SIDEBAR_SHELL_ID",
    "SIDEBAR_STATE_FORM_ID",
    "SidebarView",
    "base_document",
    "build_docs_view",
    "build_empty_view",
    "docs_href",
    "docs_shell",
    "empty_shell",
    "enhance_markdown_links",
    "extract_title",
    "floating_theme_picker",
    "htmx_nav_attrs",
    "htmx_nav_html_attrs",
    "htmx_request_href",
    "htmx_sidebar_attrs",
    "icon_href",
    "main_shell",
    "public_asset_href",
    "render_docs_fragment",
    "render_docs_page",
    "render_empty_fragment",
    "render_empty_page",
    "render_nav_items",
    "render_search_results_fragment",
    "render_sidebar_fragment",
    "search_chrome",
    "sidebar_shell",
    "theme_picker",
    "with_nav_open_paths",
]
